version: 2.1

jobs:
  job:
    parameters:
      message:
        type: string
    docker:
      - image: circleci/python:3
    steps:
      - run: echo << parameters.message >>

workflows:
  version: 2
  wf:
    jobs:
      - job:
          message: hello
          
