version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  android-repro:
    parameters:
      api-level:
        type: integer

    executor:
      name: android/android-machine
      tag: 202102-01
      resource-class: large
    
    steps:
      - android/create-avd:
          avd-name: ci-android-avd
          system-image: system-images;android-<< parameters.api-level >>;default;x86_64
          install: true

      - android/start-emulator:
          avd-name: ci-android-avd

workflows:
  test:
    jobs:
      - android-repro:
          matrix:
            parameters:
              api-level: [30, 31]
