version: 2.1

orbs:
  alex-test: aengelberg2/test-orb@0.0.2

jobs:
  job:
    parameters:
      message:
        type: string
    docker:
      - image: circleci/python:3
    steps:
      - alex-test/say-hi:
          person: Alex

workflows:
  version: 2
  wf:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - job:
          message: hello
          
