version: 2.1

jobs:
  job:
    parameters:
      message:
        type: string
    docker:
      - image: circleci/python:3
    steps:
      - run: echo hi




workflows:
  version: 2
  wf:
    jobs:
      - job:
          name: job-1
          message: hello
      - job:
          name: job-2
          message: goodbye
          requires:
            - job-1
