version: 2.1

jobs:
  job:
    parameters:
      matrix2:
        type: boolean
    docker:
      - image: circleci/python:3
    steps:
      - run: echo hi

workflows:
  wf:
    jobs:
      - job:
          matrix2: true
